import type { Metadata } from 'next';
import { Geist, Geist_Mono, IBM_Plex_Sans, Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

const interHeading = Inter({ subsets: ['latin'], variable: '--font-heading' });

const ibmPlexSans = IBM_Plex_Sans({
    subsets: ['latin'],
    variable: '--font-sans',
});

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Ekspertiza',
    description: 'Generated by create next app',
    icons: {
        icon: '/envelope.svg',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            className={cn(
                'h-full',
                'antialiased',
                geistSans.variable,
                geistMono.variable,
                'font-sans',
                ibmPlexSans.variable,
                interHeading.variable
            )}
            lang='en'
        >
            {/* <body className='flex min-h-full flex-col'> */}
            <body className='wrap-anywhere font-sans antialiased selection:bg-[rgba(79,184,178,0.24)]'>
                {children}
            </body>
        </html>
    );
}
